### ISSUE TITLE
Create cooler 2D version

### ISSUE THREAD

**Issue by richelbilderbeek** [LucKeyProductions/GameOfLifeFighter#5]
I think the 2D version can be spiced up. Because Qt does not allow drawing of QPixmaps outside of the ::paintEvent member function, I switch to SWML.

I would like to see bigger, non-(perfectly-square) tiles, where the cursor and hangars float a bit above the arena.

**Comment by richelbilderbeek** [comment]
The SFML version now shows the cell contents from images. It is however very slow. The `sf::Texture` and `sf::Sprite` instances need to be read from file only at the start of the game.

**Comment by FSX** [comment]
I ran the SFML version with a profiler and saw that there are too many draw calls. About 36000 (rough estimation) for each iteration. Only redrawing the changed tiles speeds it up. In my code in the `glgolf` directory (it was quicker to create a test from scratch), the time needed for an iteration went from 300-350ms to 28-35ms on my old computer.

**Comment by richelbilderbeek** [comment]
Awesome! Where is that pull request :-) ?

**Comment by FSX** [comment]
It's not in C++ yet. I'll try to implement it in the SFML version before 12:00, today.

**Comment by richelbilderbeek** [comment]
That would be awesome! I am fixing the controls now to fit the poster, I'll merge your work at 12:00.

**Comment by FSX** [comment]
Takes a bit more time.

**Comment by richelbilderbeek** [comment]
Okidokie, got a deadline?

**Comment by FSX** [comment]
15:00.

**Comment by richelbilderbeek** [comment]
The game does not look ugly anymore thanks to @FSX !

![gameoflifefightersfml20150925](https://cloud.githubusercontent.com/assets/2098230/10102248/b4330b20-639d-11e5-9de5-a9113c123d79.png)
