### ISSUE TITLE
Create poster

### ISSUE THREAD

**Issue by richelbilderbeek** [LucKeyProductions/GameOfLifeFighter#6]
For grrn.nl I will create a poster with game goal, GOL mechanism, controls and prefab patterns

**Comment by richelbilderbeek** [comment]
Did it: [Poster](PosterGameOfLifeFighterPoster.pdf), but please change anything you'd like

**Comment by richelbilderbeek** [comment]
@Modanung should upload his 3D version of the poster :-)

**Comment by Modanung** [comment]
Done! :8ball:
