### ISSUE TITLE
Interface change suggestion

### ISSUE THREAD

**Issue by richelbilderbeek** [LucKeyProductions/GameOfLifeFighter#7]
Now there is the member function `Game::PressKeys(std::set<Key>& keys) noexcept` that is used by all the versions. I suggest to replace it by `Game::PressKeys(const std::vector<Key>& keys) noexcept`, because:

 * Add const: Game should not be too smart and should not modify the pressed keys itself. It is dependent of the graphical library what combination of pressing and releasing keys work best
 * Convert to std::vector: a std::set loses the chronological order of key presses. It is important whether the user pressed left first and then build, or the other way around.

I suggest to fix this after the Groningen Researchers Night

**Comment by richelbilderbeek** [comment]
Added replacement already, which works under Qt version, marked older version deprecated

**Comment by richelbilderbeek** [comment]
I am going to remove the deprecated version (as I incidentally worked on it), lets see if @Modanung will complain...

**Comment by richelbilderbeek** [comment]
If no response, I will close this issue.

**Comment by Modanung** [comment]
Go ahead!
